# Generated by Django 5.2.3 on 2025-06-27 21:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPengeluaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=100)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('keterangan', models.CharField(max_length=200)),
                ('total_harga', models.PositiveIntegerField(default=0)),
                ('pengeluaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengeluaran.pengeluaran')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
